import { useEffect, useMemo, useState } from "react";
import { Crown, Gift, Save, Search, Sparkles, WalletCards, TicketPercent, Megaphone, Plus, Trash2, X } from "lucide-react";
import AdminLayout from "../layouts/AdminLayout";
import api from "../services/api";
import "../styles/clube-conceito.css";

const dinheiro=v=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const vazioCupom={codigo:"",nome:"",descricao:"",tipo:"percentual",valor:10,pedidoMinimo:0,limiteTotal:0,limitePorCliente:1,inicio:"",fim:"",ativo:true};
const vazioCampanha={nome:"",descricao:"",tipoBeneficio:"cashback",cashbackPercentual:5,multiplicadorPontos:1,pedidoMinimo:0,inicio:"",fim:"",limiteCashback:0,ativo:true};

export default function ClubeConceito(){
 const [dados,setDados]=useState(null),[cupons,setCupons]=useState([]),[campanhas,setCampanhas]=useState([]),[busca,setBusca]=useState("");
 const [aba,setAba]=useState("visao"),[msg,setMsg]=useState(""),[salvando,setSalvando]=useState(false),[modal,setModal]=useState(null),[form,setForm]=useState(null);
 async function carregar(){const [p,c,ca]=await Promise.all([api.get("/clube/painel"),api.get("/clube/cupons"),api.get("/clube/campanhas")]);setDados(p.data);setCupons(c.data.cupons||[]);setCampanhas(ca.data.campanhas||[]);}
 useEffect(()=>{carregar().catch(()=>setMsg("Não foi possível carregar o Clube Conceito."));},[]);
 const membros=useMemo(()=>(dados?.membros||[]).filter(m=>`${m.cliente.nome} ${m.cliente.telefone} ${m.cliente.numeroAssociado}`.toLowerCase().includes(busca.toLowerCase())),[dados,busca]);
 function atualizarNivel(i,campo,valor){setDados(d=>({...d,configuracao:{...d.configuracao,niveis:d.configuracao.niveis.map((n,x)=>x===i?{...n,[campo]:campo==='nome'?valor:Number(valor)}:n)}}));}
 async function salvarRegras(){setSalvando(true);try{await api.put("/clube/configuracao",dados.configuracao);setMsg("Regras salvas com sucesso.");await carregar();}catch(e){setMsg(e.response?.data?.message||"Erro ao salvar.");}finally{setSalvando(false)}}
 function abrir(tipo,item){setModal(tipo);setForm(item?{...item,inicio:item.inicio?.slice(0,10)||"",fim:item.fim?.slice(0,10)||""}:tipo==="cupom"?{...vazioCupom}:{...vazioCampanha});}
 async function salvarItem(){setSalvando(true);try{const rota=modal==="cupom"?"cupons":"campanhas";form._id?await api.put(`/clube/${rota}/${form._id}`,form):await api.post(`/clube/${rota}`,form);setModal(null);setMsg("Cadastro salvo com sucesso.");await carregar();}catch(e){setMsg(e.response?.data?.message||"Erro ao salvar cadastro.");}finally{setSalvando(false)}}
 async function excluir(tipo,id){if(!window.confirm("Excluir este cadastro?"))return;await api.delete(`/clube/${tipo}/${id}`);await carregar();}
 return <AdminLayout title="Clube Conceito" subtitle="Fidelidade, cashback, cupons e campanhas">
  <div className="cc-page">
   <header className="cc-hero"><div><span><Sparkles size={16}/> Fidelidade premium</span><h1>Clube Conceito</h1><p>Transforme cada compra em relacionamento, benefícios e novas experiências.</p></div>{aba==="regras"&&<button onClick={salvarRegras} disabled={salvando}><Save size={18}/>{salvando?"Salvando...":"Salvar regras"}</button>}</header>
   {msg&&<div className="cc-message">{msg}<button onClick={()=>setMsg("")}><X size={15}/></button></div>}
   <nav className="cc-tabs">{[["visao","Visão geral"],["regras","Regras e níveis"],["cupons","Cupons"],["campanhas","Campanhas"]].map(([id,n])=><button key={id} className={aba===id?"active":""} onClick={()=>setAba(id)}>{n}</button>)}</nav>
   {aba==="visao"&&<><section className="cc-kpis"><article><Crown/><span>Membros ativos</span><strong>{dados?.indicadores?.membros||0}</strong></article><article><Sparkles/><span>Pontos em circulação</span><strong>{Math.round(dados?.indicadores?.pontosEmCirculacao||0)}</strong></article><article><WalletCards/><span>Cashback disponível</span><strong>{dinheiro(dados?.indicadores?.cashbackEmCirculacao)}</strong></article><article><Gift/><span>Gasto acumulado</span><strong>{dinheiro(dados?.indicadores?.gastoAcumulado)}</strong></article></section><section className="cc-panel"><div className="cc-title"><div><h2>Carteiras digitais</h2><p>Visão consolidada dos membros.</p></div><div className="cc-search"><Search size={17}/><input placeholder="Buscar membro..." value={busca} onChange={e=>setBusca(e.target.value)}/></div></div><div className="cc-table-wrap"><table><thead><tr><th>Membro</th><th>Associado</th><th>Nível</th><th>Pontos</th><th>Cashback</th><th>Gasto</th></tr></thead><tbody>{membros.map(m=><tr key={m.cliente.id}><td><strong>{m.cliente.nome}</strong><small>{m.cliente.telefone}</small></td><td>{m.cliente.numeroAssociado}</td><td><span className="cc-badge">{m.nivel?.nome}</span></td><td>{Math.round(m.pontos)}</td><td>{dinheiro(m.cashback)}</td><td>{dinheiro(m.gastoAcumulado)}</td></tr>)}</tbody></table></div></section></>}
   {aba==="regras"&&<><section className="cc-panel"><div className="cc-title"><div><h2>Regras do programa</h2><p>Defina acúmulo e validade geral.</p></div></div><div className="cc-settings"><label>Nome do programa<input value={dados?.configuracao?.nomePrograma||""} onChange={e=>setDados(d=>({...d,configuracao:{...d.configuracao,nomePrograma:e.target.value}}))}/></label><label>Pontos por R$ 1<input type="number" step="0.1" value={dados?.configuracao?.pontosPorReal??1} onChange={e=>setDados(d=>({...d,configuracao:{...d.configuracao,pontosPorReal:Number(e.target.value)}}))}/></label><label>Validade dos pontos (dias)<input type="number" value={dados?.configuracao?.validadePontosDias??365} onChange={e=>setDados(d=>({...d,configuracao:{...d.configuracao,validadePontosDias:Number(e.target.value)}}))}/></label></div></section><section className="cc-panel"><div className="cc-title"><div><h2>Níveis e benefícios</h2><p>Progressão pelo gasto acumulado.</p></div></div><div className="cc-levels">{(dados?.configuracao?.niveis||[]).map((n,i)=><article key={n.nome+i}><div className="cc-level-head"><Crown/><input value={n.nome} onChange={e=>atualizarNivel(i,'nome',e.target.value)}/></div><label>Gasto mínimo<input type="number" value={n.gastoMinimo} onChange={e=>atualizarNivel(i,'gastoMinimo',e.target.value)}/></label><label>Multiplicador de pontos<input type="number" step="0.05" value={n.multiplicadorPontos} onChange={e=>atualizarNivel(i,'multiplicadorPontos',e.target.value)}/></label><label>Cashback (%)<input type="number" step="0.1" value={n.cashbackPercentual} onChange={e=>atualizarNivel(i,'cashbackPercentual',e.target.value)}/></label></article>)}</div></section></>}
   {aba==="cupons"&&<Lista titulo="Cupons inteligentes" texto="Descontos percentuais, fixos ou frete grátis." icone={<TicketPercent/>} itens={cupons} novo={()=>abrir("cupom")} editar={i=>abrir("cupom",i)} excluir={id=>excluir("cupons",id)} render={i=><><strong>{i.codigo}</strong><span>{i.nome}</span><small>{i.tipo==="percentual"?`${i.valor}%`:i.tipo==="fixo"?dinheiro(i.valor):"Frete grátis"} · {i.ativo?"Ativo":"Inativo"}</small></>}/>}
    {aba==="campanhas"&&<Lista titulo="Campanhas" texto="Pontos extras e cashback por período." icone={<Megaphone/>} itens={campanhas} novo={()=>abrir("campanha")} editar={i=>abrir("campanha",i)} excluir={id=>excluir("campanhas",id)} render={i=><><strong>{i.nome}</strong><span>{i.descricao||"Campanha promocional"}</span><small>{i.cashbackPercentual||0}% cashback · {i.multiplicadorPontos||1}x pontos · {i.ativo?"Ativa":"Inativa"}</small></>}/>}
    {modal&&<Editor tipo={modal} form={form} setForm={setForm} fechar={()=>setModal(null)} salvar={salvarItem} salvando={salvando}/>}
  </div>
 </AdminLayout>;
}
function Lista({titulo,texto,icone,itens,novo,editar,excluir,render}){return <section className="cc-panel"><div className="cc-title"><div><h2>{titulo}</h2><p>{texto}</p></div><button className="cc-new" onClick={novo}><Plus size={17}/>Novo</button></div><div className="cc-promo-grid">{itens.map(i=><article key={i._id}><div className="cc-promo-icon">{icone}</div><div className="cc-promo-info" onClick={()=>editar(i)}>{render(i)}</div><button className="cc-delete" onClick={()=>excluir(i._id)}><Trash2 size={17}/></button></article>)}{!itens.length&&<div className="cc-empty">Nenhum cadastro encontrado.</div>}</div></section>}
function Editor({tipo,form,setForm,fechar,salvar,salvando}){const set=(k,v)=>setForm(f=>({...f,[k]:v}));return <div className="cc-modal-backdrop"><div className="cc-modal"><header><div><h2>{form._id?"Editar":"Novo"} {tipo==="cupom"?"cupom":"campanha"}</h2><p>Configure as regras da promoção.</p></div><button onClick={fechar}><X/></button></header><div className="cc-form-grid">{tipo==="cupom"&&<label>Código<input value={form.codigo} onChange={e=>set("codigo",e.target.value.toUpperCase())}/></label>}<label>Nome<input value={form.nome} onChange={e=>set("nome",e.target.value)}/></label><label className="wide">Descrição<input value={form.descricao||""} onChange={e=>set("descricao",e.target.value)}/></label><label>Tipo<select value={tipo==="cupom"?form.tipo:form.tipoBeneficio} onChange={e=>set(tipo==="cupom"?"tipo":"tipoBeneficio",e.target.value)}>{tipo==="cupom"?<><option value="percentual">Percentual</option><option value="fixo">Valor fixo</option><option value="frete_gratis">Frete grátis</option></>:<><option value="cashback">Cashback</option><option value="pontos">Pontos</option><option value="pontos_cashback">Pontos + cashback</option></>}</select></label>{tipo==="cupom"?<label>Valor<input type="number" value={form.valor} onChange={e=>set("valor",Number(e.target.value))}/></label>:<><label>Cashback (%)<input type="number" value={form.cashbackPercentual} onChange={e=>set("cashbackPercentual",Number(e.target.value))}/></label><label>Multiplicador de pontos<input type="number" step="0.1" value={form.multiplicadorPontos} onChange={e=>set("multiplicadorPontos",Number(e.target.value))}/></label></>}<label>Pedido mínimo<input type="number" value={form.pedidoMinimo} onChange={e=>set("pedidoMinimo",Number(e.target.value))}/></label>{tipo==="cupom"&&<><label>Limite total<input type="number" value={form.limiteTotal} onChange={e=>set("limiteTotal",Number(e.target.value))}/></label><label>Limite por cliente<input type="number" value={form.limitePorCliente} onChange={e=>set("limitePorCliente",Number(e.target.value))}/></label></>}<label>Início<input type="date" value={form.inicio||""} onChange={e=>set("inicio",e.target.value)}/></label><label>Fim<input type="date" value={form.fim||""} onChange={e=>set("fim",e.target.value)}/></label><label className="cc-check"><input type="checkbox" checked={form.ativo!==false} onChange={e=>set("ativo",e.target.checked)}/>Ativo</label></div><footer><button className="cc-secondary" onClick={fechar}>Cancelar</button><button className="cc-primary" onClick={salvar} disabled={salvando}><Save size={17}/>{salvando?"Salvando...":"Salvar"}</button></footer></div></div>}
