const express = require("express");
const router = express.Router();
const controller = require("../controllers/clubecontroller");
router.get("/configuracao", controller.obterConfiguracao);
router.put("/configuracao", controller.salvarConfiguracao);
router.get("/painel", controller.painel);
router.get("/carteira", controller.carteira);
router.post("/movimentos", controller.lancarMovimento);
router.get("/cupons", controller.listarCupons);
router.post("/cupons", controller.salvarCupom);
router.put("/cupons/:id", controller.salvarCupom);
router.delete("/cupons/:id", controller.excluirCupom);
router.post("/cupons/validar", controller.validarCupom);
router.get("/campanhas", controller.listarCampanhas);
router.post("/campanhas", controller.salvarCampanha);
router.put("/campanhas/:id", controller.salvarCampanha);
router.delete("/campanhas/:id", controller.excluirCampanha);
router.post("/beneficios/simular", controller.simularBeneficios);
router.get("/planos", controller.listarPlanos);
router.post("/planos", controller.salvarPlano);
router.put("/planos/:id", controller.salvarPlano);
router.delete("/planos/:id", controller.excluirPlano);
router.get("/assinaturas", controller.listarAssinaturas);
router.post("/assinaturas", controller.criarAssinatura);
router.put("/assinaturas/:id", controller.atualizarAssinatura);
router.get("/assinaturas-resumo", controller.resumoAssinaturas);
router.get("/missoes", controller.listarMissoes);
router.post("/missoes", controller.salvarMissao);
router.put("/missoes/:id", controller.salvarMissao);
router.delete("/missoes/:id", controller.excluirMissao);
router.get("/gamificacao/ranking", controller.rankingGamificacao);
router.post("/gamificacao/eventos", controller.processarEventoGamificacao);
router.get("/gamificacao/clientes/:clienteId", controller.progressoCliente);
module.exports = router;
