const express = require("express");
const router = express.Router();
const controller = require("../controllers/clubecontroller");
router.get("/configuracao", controller.obterConfiguracao);
router.put("/configuracao", controller.salvarConfiguracao);
router.get("/painel", controller.painel);
router.get("/carteira", controller.carteira);
router.post("/movimentos", controller.lancarMovimento);
router.get("/cupons", controller.listarCupons);
router.post("/cupons", controller.salvarCupom);
router.put("/cupons/:id", controller.salvarCupom);
router.delete("/cupons/:id", controller.excluirCupom);
router.post("/cupons/validar", controller.validarCupom);
router.get("/campanhas", controller.listarCampanhas);
router.post("/campanhas", controller.salvarCampanha);
router.put("/campanhas/:id", controller.salvarCampanha);
router.delete("/campanhas/:id", controller.excluirCampanha);
router.post("/beneficios/simular", controller.simularBeneficios);
module.exports = router;
